name: Waka Readme

on:
  workflow_dispatch: # Trigger manually
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 UTC every day

jobs:
  update-readme:
    name: WakaReadme Coding Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: last_30_days
          SHOW_TOTAL: true
  update-redme-image:
    name: Update the WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: snaka/Profile-Readme-WakaTime@feature/add-range-parameter
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token}}
          BRANCH: main
          STATS_RANGE: last_30_days
